### ISSUE TITLE
Massa individual

### ISSUE THREAD

**Issue by mrazevedo** [levi-ufma/Stoichiometric#2]
O cálculo estequiométrico tem apresentado apenas os valores finais/somados para a massa dos reagentes e dos produtos, essa informação é útil para verificarmos a consistência do cálculo, mas não é necessário apresentá-la por padrão. 

O ideal é que sejam mostrados apenas os valores para cada composto de forma separada, como no exemplo a seguir.
Ex.: eq = "Li2CO3 + Nb2O5 -> LiNb3O8 + CO2" deve retornar as massas individuais do Li2CO3, Nb2O5, LiNb3O8 e CO2.

**Comment by jherfson** [comment]
Foi criado a função print_mass para imprimir somente o composto e a massa
